import type { ConditionEntry } from './conditionTypes';

/**
 * The family-health-condition catalog.
 *
 * Scope and wording, deliberately: this is a list of conditions where a
 * family history is *relevant to prevention*. Most are multifactorial, not
 * simple inherited disorders, and the copy never implies otherwise. Nothing
 * here diagnoses, predicts, or estimates anyone's probability of illness.
 *
 * Sources are authoritative public-health references (MedlinePlus/NIH, CDC,
 * NCI). They are given so a user can read further, not as a citation for a
 * specific numeric claim, because the app makes no numeric claims. URLs were
 * written from well-known stable topic paths and have not been fetched from
 * this build environment; treat a broken link as a content bug, not a
 * clinical one.
 */

const MEDLINEPLUS = 'MedlinePlus (NIH)';
const MP_INDEX = 'https://medlineplus.gov/healthtopics.html';
const mp = (slug: string) => `https://medlineplus.gov/${slug}.html`;

export const CONDITION_CATALOG: readonly ConditionEntry[] = [
  // --- Heart & circulation -------------------------------------------------
  {
    id: 'coronary_artery_disease',
    name: 'Coronary artery disease',
    aliases: ['heart disease', 'CAD', 'ischaemic heart disease', 'angina', 'heart attack'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'Narrowing of the arteries that supply the heart muscle.',
    riskContext:
      'Heart disease in a close relative, especially at a younger age, is one of the better established family-history signals. It raises the value of prevention; it does not mean you will develop it.',
    planTags: ['activity', 'diet-quality', 'diet-salt', 'tobacco', 'weight', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('heartdiseases'),
  },
  {
    id: 'hypertension',
    name: 'High blood pressure',
    aliases: ['hypertension', 'high BP', 'raised blood pressure'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'Blood pressure that stays higher than the healthy range over time.',
    riskContext:
      'High blood pressure clusters in families through both genetics and shared habits. Knowing this is a reason to measure it, not a diagnosis.',
    planTags: ['diet-salt', 'activity', 'weight', 'alcohol', 'sleep', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('highbloodpressure'),
  },
  {
    id: 'stroke',
    name: 'Stroke',
    aliases: ['cerebrovascular accident', 'CVA', 'brain attack', 'TIA'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'Interrupted blood supply to part of the brain.',
    riskContext:
      'Stroke in the family often reflects shared risk factors such as blood pressure. Those factors are largely modifiable.',
    planTags: ['diet-salt', 'activity', 'tobacco', 'alcohol', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('stroke'),
  },
  {
    id: 'high_cholesterol',
    name: 'High cholesterol',
    aliases: ['hyperlipidaemia', 'hyperlipidemia', 'high LDL', 'dyslipidaemia'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'Raised levels of cholesterol or other fats in the blood.',
    riskContext:
      'Some families carry an inherited pattern of very high cholesterol. A family history is a good reason to have yours checked.',
    planTags: ['diet-quality', 'activity', 'weight', 'diet-fibre'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('cholesterol'),
  },
  {
    id: 'atrial_fibrillation',
    name: 'Atrial fibrillation',
    aliases: ['AFib', 'AF', 'irregular heartbeat', 'arrhythmia'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'An irregular, often rapid heart rhythm.',
    riskContext:
      'Family history is one of several contributors alongside blood pressure, alcohol and weight.',
    planTags: ['alcohol', 'activity', 'weight', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('atrialfibrillation'),
  },
  {
    id: 'heart_failure',
    name: 'Heart failure',
    aliases: ['congestive heart failure', 'CHF', 'weak heart'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'The heart does not pump as effectively as it should.',
    riskContext:
      'Often follows other conditions such as high blood pressure or coronary disease, which themselves run in families.',
    planTags: ['diet-salt', 'activity', 'weight', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('heartfailure'),
  },
  {
    id: 'cardiomyopathy',
    name: 'Cardiomyopathy',
    aliases: ['enlarged heart', 'hypertrophic cardiomyopathy', 'HCM', 'dilated cardiomyopathy'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'Disease of the heart muscle affecting how it pumps.',
    riskContext:
      'Several forms are genuinely inherited. A family history here is worth raising with a clinician directly.',
    planTags: ['activity', 'alcohol', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('cardiomyopathy'),
  },
  {
    id: 'peripheral_artery_disease',
    name: 'Peripheral artery disease',
    aliases: ['PAD', 'poor circulation', 'claudication'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'Narrowed arteries reducing blood flow to the limbs.',
    riskContext: 'Shares its main risk factors with coronary disease, including smoking.',
    planTags: ['tobacco', 'activity', 'diet-quality', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('peripheralarterialdisease'),
  },
  {
    id: 'aortic_aneurysm',
    name: 'Aortic aneurysm',
    aliases: ['AAA', 'abdominal aortic aneurysm', 'enlarged aorta'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'A bulge in the wall of the body’s main artery.',
    riskContext:
      'Family history is a recognised factor and can affect whether screening is offered.',
    planTags: ['tobacco', 'diet-salt', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('aorticaneurysm'),
  },
  {
    id: 'venous_thromboembolism',
    name: 'Blood clots (DVT / PE)',
    aliases: ['DVT', 'deep vein thrombosis', 'pulmonary embolism', 'VTE', 'clotting disorder'],
    category: 'heart',
    familyHistoryRelevance: 'strong',
    description: 'Clots forming in deep veins, which can travel to the lungs.',
    riskContext:
      'Some inherited clotting tendencies run in families. Worth mentioning before surgery or long travel.',
    planTags: ['activity', 'hydration', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('deepveinthrombosis'),
  },
  {
    id: 'varicose_veins',
    name: 'Varicose veins',
    aliases: ['varicose', 'spider veins'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'Enlarged, visible veins, usually in the legs.',
    riskContext: 'Commonly reported across generations in the same family.',
    planTags: ['activity', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('varicoseveins'),
  },
  {
    id: 'preeclampsia',
    name: 'Pre-eclampsia',
    aliases: ['preeclampsia', 'toxaemia', 'pregnancy high blood pressure'],
    category: 'heart',
    familyHistoryRelevance: 'moderate',
    description: 'High blood pressure and related changes during pregnancy.',
    riskContext:
      'A family history in mothers or sisters is recognised. Pregnancy care should be led by a clinician.',
    planTags: ['activity', 'diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('preeclampsia'),
  },

  // --- Metabolic -----------------------------------------------------------
  {
    id: 'type2_diabetes',
    name: 'Type 2 diabetes',
    aliases: ['diabetes', 'T2D', 'adult onset diabetes', 'high blood sugar'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'The body does not use insulin effectively, raising blood glucose.',
    riskContext:
      'One of the clearest family-history signals, through both genes and shared habits. Much of the risk is modifiable.',
    planTags: ['diet-sugar', 'diet-fibre', 'activity', 'weight', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('diabetes'),
  },
  {
    id: 'type1_diabetes',
    name: 'Type 1 diabetes',
    aliases: ['T1D', 'juvenile diabetes', 'insulin dependent diabetes'],
    category: 'metabolic',
    familyHistoryRelevance: 'moderate',
    description: 'An autoimmune condition where the body stops producing insulin.',
    riskContext:
      'Not lifestyle-caused. Family history matters for awareness; management is always clinician-led.',
    planTags: ['activity', 'diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('diabetestype1'),
  },
  {
    id: 'prediabetes',
    name: 'Prediabetes',
    aliases: ['impaired glucose tolerance', 'borderline diabetes', 'insulin resistance'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'Blood glucose higher than usual but below the diabetes range.',
    riskContext:
      'Often reversible. A family history of diabetes is a good reason to have glucose checked.',
    planTags: ['diet-sugar', 'diet-fibre', 'activity', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('prediabetes'),
  },
  {
    id: 'obesity',
    name: 'Obesity',
    aliases: ['overweight', 'high BMI', 'weight gain'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'Body weight above the range associated with best health outcomes.',
    riskContext:
      'Families share genetics, food environments and habits. This is about health patterns, not appearance or blame.',
    planTags: ['diet-quality', 'diet-sugar', 'activity', 'weight', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('obesity'),
  },
  {
    id: 'metabolic_syndrome',
    name: 'Metabolic syndrome',
    aliases: ['syndrome X', 'insulin resistance syndrome'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'A cluster of blood pressure, blood sugar, waist and blood-fat findings.',
    riskContext: 'Clusters strongly in families and responds well to everyday changes.',
    planTags: ['diet-quality', 'diet-sugar', 'activity', 'weight', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('metabolicsyndrome'),
  },
  {
    id: 'thyroid_disease',
    name: 'Thyroid disease',
    aliases: ['hypothyroidism', 'hyperthyroidism', 'underactive thyroid', 'overactive thyroid', 'Hashimoto'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'The thyroid produces too little or too much hormone.',
    riskContext: 'Thyroid conditions run in families, often alongside other autoimmune conditions.',
    planTags: ['screening', 'sleep', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('thyroiddiseases'),
  },
  {
    id: 'gout',
    name: 'Gout',
    aliases: ['high uric acid', 'hyperuricaemia', 'gouty arthritis'],
    category: 'metabolic',
    familyHistoryRelevance: 'moderate',
    description: 'Crystals forming in joints, causing sudden painful attacks.',
    riskContext: 'Runs in families and is influenced by diet and alcohol.',
    planTags: ['alcohol', 'hydration', 'weight', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('gout'),
  },
  {
    id: 'fatty_liver',
    name: 'Fatty liver disease',
    aliases: ['NAFLD', 'MASLD', 'hepatic steatosis', 'liver fat'],
    category: 'metabolic',
    familyHistoryRelevance: 'moderate',
    description: 'Excess fat stored in liver cells.',
    riskContext: 'Closely tied to metabolic risk factors that cluster in families.',
    planTags: ['diet-sugar', 'alcohol', 'weight', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('fattyliverdisease'),
  },
  {
    id: 'pcos',
    name: 'Polycystic ovary syndrome',
    aliases: ['PCOS', 'polycystic ovaries'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'A hormonal condition affecting ovulation and metabolism.',
    riskContext: 'Frequently reported in mothers and sisters; often overlaps with insulin resistance.',
    planTags: ['activity', 'weight', 'diet-sugar', 'diet-fibre'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('polycysticovarysyndrome'),
  },
  {
    id: 'gestational_diabetes',
    name: 'Gestational diabetes',
    aliases: ['pregnancy diabetes', 'GDM'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'Raised blood glucose first recognised during pregnancy.',
    riskContext:
      'A family history of diabetes increases the chance it is looked for. Pregnancy care is clinician-led.',
    planTags: ['diet-sugar', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('diabetesandpregnancy'),
  },
  {
    id: 'hemochromatosis',
    name: 'Haemochromatosis',
    aliases: ['hemochromatosis', 'iron overload'],
    category: 'metabolic',
    familyHistoryRelevance: 'strong',
    description: 'The body absorbs and stores too much iron.',
    riskContext: 'A genuinely inherited condition. Relatives of someone diagnosed are often tested.',
    planTags: ['alcohol', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('hemochromatosis'),
  },

  // --- Cancer --------------------------------------------------------------
  {
    id: 'breast_cancer',
    name: 'Breast cancer',
    aliases: ['breast carcinoma', 'BRCA'],
    category: 'cancer',
    familyHistoryRelevance: 'strong',
    description: 'Cancer that begins in breast tissue.',
    riskContext:
      'A family history, particularly in a first-degree relative or at a young age, can change what screening is offered. It is not a prediction.',
    planTags: ['alcohol', 'activity', 'weight', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('breastcancer'),
  },
  {
    id: 'colorectal_cancer',
    name: 'Bowel (colorectal) cancer',
    aliases: ['colon cancer', 'rectal cancer', 'bowel cancer', 'colorectal carcinoma'],
    category: 'cancer',
    familyHistoryRelevance: 'strong',
    description: 'Cancer of the colon or rectum.',
    riskContext:
      'Family history can mean screening starts earlier. Discuss the specifics with a clinician.',
    planTags: ['diet-fibre', 'activity', 'alcohol', 'weight', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('colorectalcancer'),
  },
  {
    id: 'prostate_cancer',
    name: 'Prostate cancer',
    aliases: ['prostate carcinoma'],
    category: 'cancer',
    familyHistoryRelevance: 'strong',
    description: 'Cancer that begins in the prostate gland.',
    riskContext: 'Risk is higher when a father or brother has been affected.',
    planTags: ['activity', 'weight', 'diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('prostatecancer'),
  },
  {
    id: 'lung_cancer',
    name: 'Lung cancer',
    aliases: ['lung carcinoma'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the lungs.',
    riskContext:
      'Smoking is the dominant factor, but family history adds to it. Stopping smoking matters most.',
    planTags: ['tobacco', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('lungcancer'),
  },
  {
    id: 'ovarian_cancer',
    name: 'Ovarian cancer',
    aliases: ['ovarian carcinoma'],
    category: 'cancer',
    familyHistoryRelevance: 'strong',
    description: 'Cancer that begins in the ovaries.',
    riskContext:
      'Often considered alongside breast cancer family history; genetic counselling is sometimes offered.',
    planTags: ['activity', 'weight', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('ovariancancer'),
  },
  {
    id: 'pancreatic_cancer',
    name: 'Pancreatic cancer',
    aliases: ['pancreas cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the pancreas.',
    riskContext: 'A small share of cases cluster in families.',
    planTags: ['tobacco', 'weight', 'alcohol', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('pancreaticcancer'),
  },
  {
    id: 'stomach_cancer',
    name: 'Stomach cancer',
    aliases: ['gastric cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the stomach lining.',
    riskContext: 'Family history and some infections both contribute.',
    planTags: ['diet-salt', 'tobacco', 'diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('stomachcancer'),
  },
  {
    id: 'melanoma',
    name: 'Melanoma',
    aliases: ['skin cancer', 'malignant melanoma', 'mole cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'strong',
    description: 'A serious form of skin cancer arising from pigment cells.',
    riskContext: 'Family history, fair skin and sun exposure all contribute.',
    planTags: ['sun-safety', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('melanoma'),
  },
  {
    id: 'skin_cancer_nonmelanoma',
    name: 'Non-melanoma skin cancer',
    aliases: ['basal cell carcinoma', 'squamous cell carcinoma', 'BCC', 'SCC'],
    category: 'cancer',
    familyHistoryRelevance: 'some',
    description: 'Common skin cancers arising in the outer skin layers.',
    riskContext: 'Cumulative sun exposure is the main driver.',
    planTags: ['sun-safety', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('skincancer'),
  },
  {
    id: 'uterine_cancer',
    name: 'Uterine (endometrial) cancer',
    aliases: ['endometrial cancer', 'womb cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the lining of the uterus.',
    riskContext: 'Linked to some inherited syndromes and to metabolic risk factors.',
    planTags: ['weight', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('uterinecancer'),
  },
  {
    id: 'cervical_cancer',
    name: 'Cervical cancer',
    aliases: ['cervix cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'some',
    description: 'Cancer of the cervix, most often linked to HPV infection.',
    riskContext: 'Largely preventable through vaccination and routine screening.',
    planTags: ['screening', 'tobacco'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('cervicalcancer'),
  },
  {
    id: 'kidney_cancer',
    name: 'Kidney cancer',
    aliases: ['renal cell carcinoma', 'renal cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the kidneys.',
    riskContext: 'A few inherited syndromes raise risk; smoking and blood pressure also contribute.',
    planTags: ['tobacco', 'weight', 'diet-salt', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('kidneycancer'),
  },
  {
    id: 'liver_cancer',
    name: 'Liver cancer',
    aliases: ['hepatocellular carcinoma', 'HCC'],
    category: 'cancer',
    familyHistoryRelevance: 'some',
    description: 'Cancer that begins in the liver.',
    riskContext: 'Often follows long-standing liver damage from infection, alcohol or fatty liver.',
    planTags: ['alcohol', 'weight', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('livercancer'),
  },
  {
    id: 'thyroid_cancer',
    name: 'Thyroid cancer',
    aliases: ['thyroid carcinoma'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description: 'Cancer that begins in the thyroid gland.',
    riskContext: 'Some forms are clearly inherited and prompt family testing.',
    planTags: ['screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('thyroidcancer'),
  },
  {
    id: 'leukaemia',
    name: 'Leukaemia',
    aliases: ['leukemia', 'blood cancer', 'AML', 'CLL'],
    category: 'cancer',
    familyHistoryRelevance: 'some',
    description: 'Cancer affecting blood-forming tissue.',
    riskContext: 'Mostly not inherited; a family history is occasionally relevant.',
    planTags: ['tobacco', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('leukemia'),
  },
  {
    id: 'lymphoma',
    name: 'Lymphoma',
    aliases: ['Hodgkin lymphoma', 'non-Hodgkin lymphoma'],
    category: 'cancer',
    familyHistoryRelevance: 'some',
    description: 'Cancer of the lymphatic system.',
    riskContext: 'Family history plays a modest role for most people.',
    planTags: ['screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('lymphoma'),
  },

  {
    id: 'cancer_family_history',
    name: 'Cancer in the family (unspecified)',
    aliases: ['family history of cancer', 'cancer runs in my family', 'cancer'],
    category: 'cancer',
    familyHistoryRelevance: 'moderate',
    description:
      'A general flag that cancer has occurred in close blood relatives, without naming which type.',
    riskContext:
      'Pick this if you know cancer is in your family but would rather not record which kind. It is deliberately non-specific: Preventah never asks which relative or any clinical detail. A clinician can tell you whether the pattern in your family warrants specific screening.',
    planTags: ['tobacco', 'alcohol', 'weight', 'activity', 'diet-quality', 'diet-fibre', 'screening', 'sun-safety'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('cancer'),
  },

  // --- Neurological --------------------------------------------------------
  {
    id: 'alzheimers',
    name: "Alzheimer's disease",
    aliases: ['alzheimers', 'dementia', 'memory loss'],
    category: 'neurological',
    familyHistoryRelevance: 'strong',
    description: 'A progressive condition affecting memory and thinking.',
    riskContext:
      'Family history raises risk but is far from determinative. Cardiovascular health, activity and sleep all matter.',
    planTags: ['activity', 'sleep', 'diet-quality', 'mental-wellbeing'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('alzheimersdisease'),
  },
  {
    id: 'parkinsons',
    name: "Parkinson's disease",
    aliases: ['parkinsons', 'PD', 'tremor'],
    category: 'neurological',
    familyHistoryRelevance: 'moderate',
    description: 'A progressive condition affecting movement.',
    riskContext: 'Most cases are not inherited; a minority cluster in families.',
    planTags: ['activity', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('parkinsonsdisease'),
  },
  {
    id: 'migraine',
    name: 'Migraine',
    aliases: ['migraines', 'severe headache', 'headache disorder'],
    category: 'neurological',
    familyHistoryRelevance: 'strong',
    description: 'Recurrent headaches, often with sensitivity to light or sound.',
    riskContext: 'Migraine runs strongly in families. Triggers are often identifiable and personal.',
    planTags: ['sleep', 'hydration', 'stress', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('migraine'),
  },
  {
    id: 'epilepsy',
    name: 'Epilepsy',
    aliases: ['seizures', 'seizure disorder'],
    category: 'neurological',
    familyHistoryRelevance: 'moderate',
    description: 'A tendency to recurrent seizures.',
    riskContext: 'Some forms have a genetic component. Management is always clinician-led.',
    planTags: ['sleep', 'alcohol', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('epilepsy'),
  },
  {
    id: 'multiple_sclerosis',
    name: 'Multiple sclerosis',
    aliases: ['MS'],
    category: 'neurological',
    familyHistoryRelevance: 'moderate',
    description: 'An immune-mediated condition affecting nerve signalling.',
    riskContext: 'Risk is modestly higher with an affected close relative.',
    planTags: ['activity', 'sleep', 'tobacco'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('multiplesclerosis'),
  },
  {
    id: 'essential_tremor',
    name: 'Essential tremor',
    aliases: ['familial tremor', 'shaking hands'],
    category: 'neurological',
    familyHistoryRelevance: 'strong',
    description: 'A common movement condition causing rhythmic shaking.',
    riskContext: 'Frequently inherited and often reported across generations.',
    planTags: ['alcohol', 'sleep', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('essentialtremor'),
  },
  {
    id: 'huntingtons',
    name: "Huntington's disease",
    aliases: ['huntingtons', 'HD'],
    category: 'neurological',
    familyHistoryRelevance: 'strong',
    description: 'An inherited condition affecting movement, thinking and mood.',
    riskContext:
      'Directly inherited. Genetic counselling is the right route for anyone with it in the family.',
    planTags: ['activity', 'mental-wellbeing', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('huntingtonsdisease'),
  },
  {
    id: 'neuropathy',
    name: 'Peripheral neuropathy',
    aliases: ['nerve damage', 'numbness', 'tingling'],
    category: 'neurological',
    familyHistoryRelevance: 'some',
    description: 'Damage to nerves outside the brain and spinal cord.',
    riskContext: 'Often follows diabetes; some inherited forms exist.',
    planTags: ['diet-sugar', 'alcohol', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('peripheralnervedisorders'),
  },
  {
    id: 'restless_legs',
    name: 'Restless legs syndrome',
    aliases: ['RLS', 'restless leg'],
    category: 'neurological',
    familyHistoryRelevance: 'strong',
    description: 'An urge to move the legs, usually worse at rest.',
    riskContext: 'Commonly reported in several family members.',
    planTags: ['sleep', 'activity', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('restlesslegs'),
  },

  // --- Respiratory ---------------------------------------------------------
  {
    id: 'asthma',
    name: 'Asthma',
    aliases: ['wheeze', 'reactive airway'],
    category: 'respiratory',
    familyHistoryRelevance: 'strong',
    description: 'Airways that narrow and inflame in response to triggers.',
    riskContext: 'Runs in families, often alongside eczema and hay fever.',
    planTags: ['breathing', 'tobacco', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('asthma'),
  },
  {
    id: 'copd',
    name: 'COPD',
    aliases: ['chronic obstructive pulmonary disease', 'emphysema', 'chronic bronchitis'],
    category: 'respiratory',
    familyHistoryRelevance: 'moderate',
    description: 'Long-term airflow obstruction, usually from lung damage.',
    riskContext: 'Smoking dominates; a rare inherited deficiency also contributes.',
    planTags: ['tobacco', 'breathing', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('copd'),
  },
  {
    id: 'sleep_apnoea',
    name: 'Sleep apnoea',
    aliases: ['sleep apnea', 'OSA', 'snoring', 'obstructive sleep apnoea'],
    category: 'respiratory',
    familyHistoryRelevance: 'moderate',
    description: 'Breathing repeatedly pauses during sleep.',
    riskContext: 'Family patterns exist through build and airway shape as well as weight.',
    planTags: ['sleep', 'weight', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('sleepapnea'),
  },
  {
    id: 'allergic_rhinitis',
    name: 'Hay fever',
    aliases: ['allergic rhinitis', 'pollen allergy', 'seasonal allergy'],
    category: 'respiratory',
    familyHistoryRelevance: 'strong',
    description: 'Allergic inflammation of the nose and eyes.',
    riskContext: 'Strongly familial and often appears with asthma or eczema.',
    planTags: ['breathing', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('hayfever'),
  },
  {
    id: 'pulmonary_fibrosis',
    name: 'Pulmonary fibrosis',
    aliases: ['IPF', 'lung scarring', 'interstitial lung disease'],
    category: 'respiratory',
    familyHistoryRelevance: 'moderate',
    description: 'Scarring of lung tissue that stiffens the lungs.',
    riskContext: 'A familial form is recognised in a minority of cases.',
    planTags: ['tobacco', 'breathing', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('pulmonaryfibrosis'),
  },
  {
    id: 'bronchiectasis',
    name: 'Bronchiectasis',
    aliases: ['widened airways', 'chronic chest infection'],
    category: 'respiratory',
    familyHistoryRelevance: 'some',
    description: 'Permanently widened airways prone to infection.',
    riskContext: 'Sometimes follows inherited conditions such as cystic fibrosis.',
    planTags: ['breathing', 'tobacco', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },

  // --- Blood & genetic -----------------------------------------------------
  {
    id: 'sickle_cell_disease',
    name: 'Sickle cell disease',
    aliases: ['sickle cell anaemia', 'sickle cell anemia', 'SCD', 'sickle cell trait'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited condition in which red blood cells take a rigid, curved shape.',
    riskContext:
      'This one really is inherited, passed on when both parents carry the trait. If it runs in your family, carrier testing and specialist care matter far more than any lifestyle change; the habits below only support general wellbeing.',
    planTags: ['hydration', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('sicklecelldisease'),
  },
  {
    id: 'thalassaemia',
    name: 'Thalassaemia',
    aliases: ['thalassemia', 'Mediterranean anaemia', 'beta thalassaemia'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited condition affecting how the body makes haemoglobin.',
    riskContext:
      'Inherited from carrier parents and more common in some ancestries. Family history here is a reason to ask about carrier testing, not something diet can change.',
    planTags: ['diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('thalassemia'),
  },
  {
    id: 'haemophilia',
    name: 'Haemophilia',
    aliases: ['hemophilia', 'bleeding disorder', 'factor VIII deficiency'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited bleeding disorder in which blood does not clot normally.',
    riskContext:
      'Usually passed down through families in a well understood pattern. Knowing it runs in yours is medically useful information to share with any clinician before a procedure.',
    planTags: ['activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('hemophilia'),
  },
  {
    id: 'von_willebrand_disease',
    name: 'Von Willebrand disease',
    aliases: ['VWD', 'easy bruising disorder', 'bleeding disorder'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'The most common inherited bleeding disorder, affecting clotting.',
    riskContext:
      'Frequently mild and undiagnosed for years, so a relative with unexplained heavy bleeding is worth mentioning to a clinician.',
    planTags: ['screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('vonwillebranddisease'),
  },
  {
    id: 'g6pd_deficiency',
    name: 'G6PD deficiency',
    aliases: ['glucose-6-phosphate dehydrogenase deficiency', 'favism'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited enzyme difference that can make red blood cells break down after certain triggers.',
    riskContext:
      'Inherited, and mostly silent until a trigger such as a particular medicine or food. Family history is a reason to know your status before taking certain drugs.',
    planTags: ['screening', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
  {
    id: 'hereditary_spherocytosis',
    name: 'Hereditary spherocytosis',
    aliases: ['spherocytosis', 'inherited haemolytic anaemia'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited condition that makes red blood cells fragile and short-lived.',
    riskContext:
      'Runs in families directly. It is managed medically; the habits here support general health rather than treating it.',
    planTags: ['diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
  {
    id: 'factor_v_leiden',
    name: 'Inherited clotting tendency',
    aliases: ['factor V Leiden', 'thrombophilia', 'clotting disorder', 'prothrombin mutation'],
    category: 'blood',
    familyHistoryRelevance: 'strong',
    description: 'An inherited difference that makes blood somewhat more likely to clot.',
    riskContext:
      'Most carriers never have a clot. It matters most around surgery, pregnancy and long journeys, which is exactly why knowing about it is useful.',
    planTags: ['activity', 'hydration', 'weight', 'tobacco'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('bloodclots'),
  },
  {
    id: 'iron_deficiency_anaemia',
    name: 'Iron deficiency anaemia',
    aliases: ['iron deficiency anemia', 'low iron', 'low haemoglobin'],
    category: 'blood',
    familyHistoryRelevance: 'some',
    description: 'Too little iron to make enough healthy red blood cells.',
    riskContext:
      'Usually about diet, blood loss or absorption rather than genes, though it can cluster in families through shared diets and through inherited causes of blood loss.',
    planTags: ['diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('irondeficiencyanemia'),
  },
  {
    id: 'pernicious_anaemia',
    name: 'Pernicious anaemia',
    aliases: ['pernicious anemia', 'B12 deficiency', 'vitamin B12 anaemia'],
    category: 'blood',
    familyHistoryRelevance: 'moderate',
    description: 'Anaemia caused by the body being unable to absorb vitamin B12.',
    riskContext:
      'Has an autoimmune basis and tends to run in families alongside other autoimmune conditions. Picked up with a simple blood test.',
    planTags: ['diet-quality', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('perniciousanemia'),
  },

  // --- Autoimmune ----------------------------------------------------------
  {
    id: 'rheumatoid_arthritis',
    name: 'Rheumatoid arthritis',
    aliases: ['RA', 'inflammatory arthritis'],
    category: 'autoimmune',
    familyHistoryRelevance: 'moderate',
    description: 'An autoimmune condition in which the immune system attacks the joint lining.',
    riskContext:
      'Family history raises the odds somewhat. Not smoking is the single best established modifiable factor.',
    planTags: ['tobacco', 'activity', 'weight', 'diet-quality', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('rheumatoidarthritis'),
  },
  {
    id: 'lupus',
    name: 'Lupus',
    aliases: ['SLE', 'systemic lupus erythematosus'],
    category: 'autoimmune',
    familyHistoryRelevance: 'moderate',
    description: 'An autoimmune condition that can affect skin, joints and internal organs.',
    riskContext:
      'Clusters in families and is more common in some groups. Most relatives of someone with lupus never develop it.',
    planTags: ['sun-safety', 'stress', 'sleep', 'activity', 'tobacco'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('lupus'),
  },
  {
    id: 'psoriasis',
    name: 'Psoriasis',
    aliases: ['plaque psoriasis', 'scaly skin condition'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'An immune-driven skin condition causing patches of thickened, scaly skin.',
    riskContext:
      'One of the more clearly familial skin conditions. Weight, alcohol and smoking all influence how severe it becomes.',
    planTags: ['weight', 'alcohol', 'tobacco', 'stress', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('psoriasis'),
  },
  {
    id: 'psoriatic_arthritis',
    name: 'Psoriatic arthritis',
    aliases: ['PsA', 'arthritis with psoriasis'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'Joint inflammation that occurs in some people who have psoriasis.',
    riskContext:
      'Strongly familial, usually alongside psoriasis itself. Keeping weight and activity in a good place protects the joints.',
    planTags: ['weight', 'activity', 'tobacco', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('psoriaticarthritis'),
  },
  {
    id: 'coeliac_disease',
    name: 'Coeliac disease',
    aliases: ['celiac disease', 'gluten intolerance', 'gluten sensitive enteropathy'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'An immune reaction to gluten that damages the lining of the small intestine.',
    riskContext:
      'First-degree relatives are tested for good reason. This is one where a family history genuinely changes what a clinician would suggest.',
    planTags: ['diet-quality', 'gut-health', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('celiacdisease'),
  },
  {
    id: 'hashimotos_thyroiditis',
    name: "Hashimoto's thyroiditis",
    aliases: ['Hashimotos', 'autoimmune thyroiditis', 'underactive thyroid'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'An autoimmune condition that gradually reduces thyroid hormone production.',
    riskContext:
      'Runs strongly in families, often alongside other autoimmune conditions. A blood test settles it.',
    planTags: ['screening', 'diet-quality', 'sleep', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('hashimotosdisease'),
  },
  {
    id: 'graves_disease',
    name: "Graves' disease",
    aliases: ['Graves disease', 'overactive thyroid', 'hyperthyroidism'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'An autoimmune condition that makes the thyroid overactive.',
    riskContext:
      'Familial clustering is well recognised, and smoking makes the eye complications worse.',
    planTags: ['tobacco', 'screening', 'stress', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('gravesdisease'),
  },
  {
    id: 'vitiligo',
    name: 'Vitiligo',
    aliases: ['skin depigmentation', 'white patches'],
    category: 'autoimmune',
    familyHistoryRelevance: 'moderate',
    description: 'An autoimmune condition in which patches of skin lose their pigment.',
    riskContext:
      'Often runs in families and travels with other autoimmune conditions. Depigmented skin burns easily, so sun protection matters.',
    planTags: ['sun-safety', 'stress', 'mental-wellbeing'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('vitiligo'),
  },
  {
    id: 'ankylosing_spondylitis',
    name: 'Ankylosing spondylitis',
    aliases: ['axial spondyloarthritis', 'AS', 'inflammatory back pain'],
    category: 'autoimmune',
    familyHistoryRelevance: 'strong',
    description: 'Inflammatory arthritis mainly affecting the spine and pelvis.',
    riskContext:
      'Has one of the stronger genetic associations in this list. Persistent early-morning back stiffness in a young adult with a family history is worth investigating.',
    planTags: ['activity', 'tobacco', 'bone-strength', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('ankylosingspondylitis'),
  },

  // --- Bone & connective tissue --------------------------------------------
  {
    id: 'osteoporosis',
    name: 'Osteoporosis',
    aliases: ['brittle bones', 'low bone density', 'thin bones'],
    category: 'bone',
    familyHistoryRelevance: 'strong',
    description: 'Bone that has become less dense and more likely to fracture.',
    riskContext:
      'A parent who broke a hip is a recognised risk marker. Bone responds to loading and to calcium and vitamin D, so this is one of the more actionable entries here.',
    planTags: ['bone-strength', 'activity', 'diet-quality', 'tobacco', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('osteoporosis'),
  },
  {
    id: 'osteoarthritis',
    name: 'Osteoarthritis',
    aliases: ['wear and tear arthritis', 'degenerative joint disease', 'OA'],
    category: 'bone',
    familyHistoryRelevance: 'moderate',
    description: 'Gradual breakdown of the cartilage that cushions a joint.',
    riskContext:
      'Hand and knee osteoarthritis both show familial patterns. Body weight and muscle strength around the joint are the levers you hold.',
    planTags: ['weight', 'activity', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('osteoarthritis'),
  },
  {
    id: 'marfan_syndrome',
    name: 'Marfan syndrome',
    aliases: ['connective tissue disorder', 'Marfans'],
    category: 'bone',
    familyHistoryRelevance: 'strong',
    description: 'An inherited connective tissue disorder affecting the heart, eyes and skeleton.',
    riskContext:
      'Directly inherited in most cases. Family history here means cardiac and eye surveillance, which is exactly the kind of thing worth raising with a clinician.',
    planTags: ['screening', 'eye-care', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('marfansyndrome'),
  },
  {
    id: 'ehlers_danlos',
    name: 'Ehlers-Danlos syndrome',
    aliases: ['EDS', 'hypermobility syndrome', 'joint hypermobility'],
    category: 'bone',
    familyHistoryRelevance: 'strong',
    description: 'A group of inherited conditions affecting connective tissue, joints and skin.',
    riskContext:
      'Inherited, and often recognised only after several relatives compare notes. Strength work around loose joints is the mainstay of self-management.',
    planTags: ['activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
  {
    id: 'scoliosis',
    name: 'Scoliosis',
    aliases: ['curved spine', 'spinal curvature'],
    category: 'bone',
    familyHistoryRelevance: 'moderate',
    description: 'A sideways curve of the spine, usually appearing during growth.',
    riskContext:
      'Tends to run in families. Early detection in a growing child is what changes the outcome.',
    planTags: ['activity', 'screening', 'bone-strength'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('scoliosis'),
  },
  {
    id: 'hip_dysplasia',
    name: 'Hip dysplasia',
    aliases: ['developmental dysplasia of the hip', 'shallow hip socket'],
    category: 'bone',
    familyHistoryRelevance: 'moderate',
    description: 'A hip socket that does not fully cover the ball of the joint.',
    riskContext:
      'Familial clustering is well described, and it is a common reason for early hip arthritis in adults.',
    planTags: ['activity', 'weight', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
  {
    id: 'dupuytrens_contracture',
    name: "Dupuytren's contracture",
    aliases: ['Dupuytrens', 'bent finger', 'palmar fibromatosis'],
    category: 'bone',
    familyHistoryRelevance: 'strong',
    description: 'Thickening of tissue in the palm that gradually bends the fingers inward.',
    riskContext:
      'Strongly familial and more common in some northern European ancestries. Alcohol and smoking are associated with it.',
    planTags: ['alcohol', 'tobacco', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
  {
    id: 'fibromyalgia',
    name: 'Fibromyalgia',
    aliases: ['widespread pain syndrome', 'chronic widespread pain'],
    category: 'bone',
    familyHistoryRelevance: 'moderate',
    description: 'Persistent widespread pain, often with fatigue and poor sleep.',
    riskContext:
      'Familial clustering is reported. Sleep quality and graded activity are the best supported self-management levers.',
    planTags: ['sleep', 'activity', 'stress', 'mental-wellbeing'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('fibromyalgia'),
  },

  // --- Digestive -----------------------------------------------------------
  {
    id: 'crohns_disease',
    name: "Crohn's disease",
    aliases: ['Crohns', 'inflammatory bowel disease', 'IBD'],
    category: 'digestive',
    familyHistoryRelevance: 'strong',
    description: 'Chronic inflammation that can affect any part of the digestive tract.',
    riskContext:
      'One of the more clearly familial digestive conditions. Not smoking matters a great deal for how it behaves.',
    planTags: ['tobacco', 'gut-health', 'diet-quality', 'stress', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('crohnsdisease'),
  },
  {
    id: 'ulcerative_colitis',
    name: 'Ulcerative colitis',
    aliases: ['UC', 'inflammatory bowel disease', 'colitis'],
    category: 'digestive',
    familyHistoryRelevance: 'strong',
    description: 'Chronic inflammation and ulceration of the lining of the large bowel.',
    riskContext:
      'Runs in families alongside other inflammatory bowel disease. Long-standing colitis also changes bowel cancer screening advice.',
    planTags: ['gut-health', 'diet-fibre', 'screening', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('ulcerativecolitis'),
  },
  {
    id: 'irritable_bowel_syndrome',
    name: 'Irritable bowel syndrome',
    aliases: ['IBS', 'spastic colon', 'nervous stomach'],
    category: 'digestive',
    familyHistoryRelevance: 'moderate',
    description: 'A long-term pattern of abdominal pain with changes in bowel habit.',
    riskContext:
      'Tends to cluster in families through a mix of biology and shared environment. Fibre, stress and sleep all move the needle.',
    planTags: ['diet-fibre', 'gut-health', 'stress', 'hydration', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('irritablebowelsyndrome'),
  },
  {
    id: 'gerd',
    name: 'Acid reflux',
    aliases: ['GERD', 'GORD', 'heartburn', 'gastro-oesophageal reflux'],
    category: 'digestive',
    familyHistoryRelevance: 'moderate',
    description: 'Stomach acid moving back up into the gullet, causing heartburn.',
    riskContext:
      'Familial patterns exist, and long-standing reflux is worth reporting because it can change the lining of the oesophagus over time.',
    planTags: ['weight', 'diet-quality', 'alcohol', 'tobacco', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('gerd'),
  },
  {
    id: 'gallstones',
    name: 'Gallstones',
    aliases: ['gallbladder stones', 'cholelithiasis', 'biliary colic'],
    category: 'digestive',
    familyHistoryRelevance: 'moderate',
    description: 'Hardened deposits that form in the gallbladder.',
    riskContext:
      'A family history is a recognised factor, as is rapid weight loss. Steady weight change is kinder to the gallbladder than crash dieting.',
    planTags: ['weight', 'diet-quality', 'diet-fibre', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('gallstones'),
  },
  {
    id: 'diverticular_disease',
    name: 'Diverticular disease',
    aliases: ['diverticulosis', 'diverticulitis', 'bowel pouches'],
    category: 'digestive',
    familyHistoryRelevance: 'moderate',
    description: 'Small pouches forming in the wall of the large bowel, which can become inflamed.',
    riskContext:
      'Both genes and a lifetime of low-fibre eating contribute, and families tend to share the second.',
    planTags: ['diet-fibre', 'hydration', 'activity', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('diverticulosisanddiverticulitis'),
  },
  {
    id: 'lactose_intolerance',
    name: 'Lactose intolerance',
    aliases: ['milk intolerance', 'lactase deficiency', 'dairy intolerance'],
    category: 'digestive',
    familyHistoryRelevance: 'strong',
    description: 'Difficulty digesting the sugar in milk, causing bloating and discomfort.',
    riskContext:
      'Largely determined by ancestry and inheritance rather than anything you did. The practical concern is getting enough calcium from other sources.',
    planTags: ['diet-quality', 'bone-strength', 'gut-health'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('lactoseintolerance'),
  },
  {
    id: 'pancreatitis',
    name: 'Pancreatitis',
    aliases: ['inflamed pancreas', 'chronic pancreatitis'],
    category: 'digestive',
    familyHistoryRelevance: 'moderate',
    description: 'Inflammation of the pancreas, which can be sudden or long-standing.',
    riskContext:
      'A rare inherited form exists, and gallstones and alcohol account for most other cases. Alcohol is the clearest lever.',
    planTags: ['alcohol', 'tobacco', 'diet-quality', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('pancreatitis'),
  },
  {
    id: 'peptic_ulcer',
    name: 'Peptic ulcer',
    aliases: ['stomach ulcer', 'duodenal ulcer', 'H pylori'],
    category: 'digestive',
    familyHistoryRelevance: 'some',
    description: 'A sore in the lining of the stomach or upper small intestine.',
    riskContext:
      'Families often share the H. pylori infection behind many ulcers, which is treatable once identified.',
    planTags: ['tobacco', 'alcohol', 'diet-quality', 'screening', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('pepticulcer'),
  },

  // --- Kidney & urinary ----------------------------------------------------
  {
    id: 'chronic_kidney_disease',
    name: 'Chronic kidney disease',
    aliases: ['CKD', 'kidney failure', 'renal disease', 'reduced kidney function'],
    category: 'kidney',
    familyHistoryRelevance: 'strong',
    description: 'A long-term reduction in how well the kidneys filter blood.',
    riskContext:
      'Runs in families both directly and through diabetes and blood pressure. Those two are where prevention actually happens.',
    planTags: ['diet-salt', 'hydration', 'weight', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('chronickidneydisease'),
  },
  {
    id: 'polycystic_kidney_disease',
    name: 'Polycystic kidney disease',
    aliases: ['PKD', 'kidney cysts', 'ADPKD'],
    category: 'kidney',
    familyHistoryRelevance: 'strong',
    description: 'An inherited condition in which cysts grow in the kidneys.',
    riskContext:
      'Directly inherited, commonly in a pattern where each child of an affected parent has a meaningful chance. Blood pressure control slows it.',
    planTags: ['diet-salt', 'hydration', 'screening', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('polycystickidneydisease'),
  },
  {
    id: 'kidney_stones',
    name: 'Kidney stones',
    aliases: ['renal stones', 'nephrolithiasis', 'urinary stones'],
    category: 'kidney',
    familyHistoryRelevance: 'strong',
    description: 'Hard deposits that form in the kidneys and can be very painful to pass.',
    riskContext:
      'A family history roughly doubles the chance, and fluid intake is the single most effective preventive habit.',
    planTags: ['hydration', 'diet-salt', 'diet-quality', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('kidneystones'),
  },
  {
    id: 'recurrent_uti',
    name: 'Recurrent urinary tract infections',
    aliases: ['UTI', 'bladder infection', 'cystitis'],
    category: 'kidney',
    familyHistoryRelevance: 'moderate',
    description: 'Urinary infections that keep coming back.',
    riskContext:
      'A maternal history of recurrent infections is a recognised pattern. Hydration is the simplest supportive habit.',
    planTags: ['hydration', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('urinarytractinfections'),
  },
  {
    id: 'enlarged_prostate',
    name: 'Enlarged prostate',
    aliases: ['BPH', 'benign prostatic hyperplasia', 'prostate enlargement'],
    category: 'kidney',
    familyHistoryRelevance: 'moderate',
    description: 'Non-cancerous growth of the prostate that can affect urination.',
    riskContext:
      'Common with age and more likely with a family history. It is not prostate cancer, though the symptoms overlap enough to be worth checking.',
    planTags: ['activity', 'weight', 'screening', 'hydration'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('enlargedprostatebph'),
  },
  {
    id: 'urinary_incontinence',
    name: 'Urinary incontinence',
    aliases: ['bladder leakage', 'stress incontinence', 'overactive bladder'],
    category: 'kidney',
    familyHistoryRelevance: 'moderate',
    description: 'Loss of bladder control, ranging from occasional leaks to urgency.',
    riskContext:
      'Familial patterns are described, particularly in women. Pelvic floor training and weight both help and are rarely offered early enough.',
    planTags: ['activity', 'weight', 'hydration'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('urinaryincontinence'),
  },

  // --- Eye & vision --------------------------------------------------------
  {
    id: 'glaucoma',
    name: 'Glaucoma',
    aliases: ['raised eye pressure', 'optic nerve damage'],
    category: 'vision',
    familyHistoryRelevance: 'strong',
    description: 'Damage to the optic nerve, often linked to pressure inside the eye.',
    riskContext:
      'A first-degree relative with glaucoma substantially raises risk, and it is painless until sight is already lost. This is a textbook case for regular eye tests.',
    planTags: ['eye-care', 'screening', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('glaucoma'),
  },
  {
    id: 'macular_degeneration',
    name: 'Age-related macular degeneration',
    aliases: ['AMD', 'macular degeneration', 'central vision loss'],
    category: 'vision',
    familyHistoryRelevance: 'strong',
    description: 'Deterioration of the central part of the retina, affecting detailed vision.',
    riskContext:
      'One of the more strongly heritable eye conditions. Smoking is the standout modifiable factor.',
    planTags: ['tobacco', 'eye-care', 'diet-quality', 'sun-safety', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('maculardegeneration'),
  },
  {
    id: 'cataract',
    name: 'Cataract',
    aliases: ['clouded lens', 'cataracts'],
    category: 'vision',
    familyHistoryRelevance: 'moderate',
    description: 'Clouding of the lens of the eye, blurring vision.',
    riskContext:
      'Very common with age, with some familial tendency. Sun protection and not smoking both delay it.',
    planTags: ['sun-safety', 'tobacco', 'eye-care', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('cataract'),
  },
  {
    id: 'diabetic_retinopathy',
    name: 'Diabetic eye disease',
    aliases: ['diabetic retinopathy', 'retinopathy', 'diabetic eye problems'],
    category: 'vision',
    familyHistoryRelevance: 'moderate',
    description: 'Damage to the blood vessels of the retina caused by diabetes.',
    riskContext:
      'Follows diabetes, which itself runs in families. Blood glucose control and annual eye screening are what protect sight.',
    planTags: ['diet-sugar', 'eye-care', 'screening', 'activity', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('diabeticeyeproblems'),
  },
  {
    id: 'myopia',
    name: 'Short-sightedness',
    aliases: ['myopia', 'nearsightedness', 'short sighted'],
    category: 'vision',
    familyHistoryRelevance: 'strong',
    description: 'Distant objects appear blurred because of how the eye focuses light.',
    riskContext:
      'Strongly familial, and high myopia carries its own long-term eye risks. Time outdoors in childhood is protective.',
    planTags: ['eye-care', 'activity', 'screening'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('nearsightedness'),
  },
  {
    id: 'retinitis_pigmentosa',
    name: 'Retinitis pigmentosa',
    aliases: ['RP', 'inherited retinal disease', 'night blindness'],
    category: 'vision',
    familyHistoryRelevance: 'strong',
    description: 'A group of inherited conditions causing gradual loss of retinal cells.',
    riskContext:
      'Directly inherited. Family history means specialist assessment rather than anything a habit can change.',
    planTags: ['eye-care', 'screening', 'sun-safety'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },

  // --- Mental & behavioural ------------------------------------------------
  {
    id: 'depression',
    name: 'Depression',
    aliases: ['major depressive disorder', 'clinical depression', 'low mood'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'Persistent low mood and loss of interest that affects daily life.',
    riskContext:
      'Depression in a close relative raises risk meaningfully. It also makes early recognition easier, which is worth something. This app is not a substitute for care.',
    planTags: ['mental-wellbeing', 'activity', 'sleep', 'alcohol', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('depression'),
  },
  {
    id: 'anxiety_disorder',
    name: 'Anxiety disorder',
    aliases: ['generalised anxiety', 'panic disorder', 'anxiety'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'Anxiety that is persistent, out of proportion, and interferes with life.',
    riskContext:
      'Runs in families through both inheritance and learned patterns. Sleep, movement and alcohol all influence it.',
    planTags: ['mental-wellbeing', 'stress', 'sleep', 'activity', 'alcohol'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('anxiety'),
  },
  {
    id: 'bipolar_disorder',
    name: 'Bipolar disorder',
    aliases: ['manic depression', 'bipolar'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'A condition involving episodes of both depressed and elevated mood.',
    riskContext:
      'Among the most heritable mental health conditions. A family history is a reason to protect sleep and to seek help early, not a forecast.',
    planTags: ['sleep', 'mental-wellbeing', 'alcohol', 'stress', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('bipolardisorder'),
  },
  {
    id: 'schizophrenia',
    name: 'Schizophrenia',
    aliases: ['psychosis', 'psychotic disorder'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'A condition affecting thinking, perception and sense of reality.',
    riskContext:
      'Heritable, though most people with an affected relative never develop it. Early help changes outcomes considerably.',
    planTags: ['mental-wellbeing', 'sleep', 'activity', 'tobacco'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('schizophrenia'),
  },
  {
    id: 'adhd',
    name: 'ADHD',
    aliases: ['attention deficit hyperactivity disorder', 'attention deficit disorder', 'ADD'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'A developmental difference in attention, activity and impulse regulation.',
    riskContext:
      'Highly familial, and often recognised in a parent only after a child is assessed. Sleep and routine matter more here than most people expect.',
    planTags: ['sleep', 'activity', 'mental-wellbeing', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('attentiondeficithyperactivitydisorder'),
  },
  {
    id: 'autism_spectrum',
    name: 'Autism spectrum condition',
    aliases: ['autism', 'ASD', 'autistic spectrum disorder'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'A lifelong developmental difference in communication, sensory processing and social interaction.',
    riskContext:
      'Clearly familial. Listed here because families often want that acknowledged; it is a difference to understand and support, not an illness to prevent.',
    planTags: ['mental-wellbeing', 'sleep', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('autismspectrumdisorder'),
  },
  {
    id: 'eating_disorder',
    name: 'Eating disorder',
    aliases: ['anorexia', 'bulimia', 'binge eating disorder'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'A serious condition involving disturbed eating behaviour and body image.',
    riskContext:
      'Runs in families. If this is in yours, weight-focused goals can do harm, which is why Preventah tracks habits rather than setting weight targets.',
    planTags: ['mental-wellbeing', 'stress', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('eatingdisorders'),
  },
  {
    id: 'alcohol_use_disorder',
    name: 'Alcohol use disorder',
    aliases: ['alcoholism', 'problem drinking', 'alcohol dependence'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'Drinking that has become difficult to control and is causing harm.',
    riskContext:
      'Family history is one of the stronger risk markers, through both inheritance and environment. It is also one of the most changeable.',
    planTags: ['alcohol', 'mental-wellbeing', 'stress', 'sleep', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('alcoholusedisorderaud'),
  },
  {
    id: 'ocd',
    name: 'Obsessive-compulsive disorder',
    aliases: ['OCD', 'obsessive compulsive disorder', 'intrusive thoughts'],
    category: 'mental',
    familyHistoryRelevance: 'strong',
    description: 'Unwanted repetitive thoughts paired with compulsions to act on them.',
    riskContext:
      'Familial clustering is well established, particularly when it starts in childhood. Effective treatment exists.',
    planTags: ['mental-wellbeing', 'stress', 'sleep'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('obsessivecompulsivedisorder'),
  },

  // --- Other ---------------------------------------------------------------
  {
    id: 'hearing_loss',
    name: 'Hearing loss',
    aliases: ['deafness', 'hard of hearing', 'age-related hearing loss', 'presbycusis'],
    category: 'other',
    familyHistoryRelevance: 'strong',
    description: 'Reduced hearing, whether inherited, age-related or noise-induced.',
    riskContext:
      'Both inherited forms and age-related hearing loss cluster in families. Protecting your ears from loud noise is the part you control.',
    planTags: ['screening', 'mental-wellbeing'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('hearingdisordersanddeafness'),
  },
  {
    id: 'periodontal_disease',
    name: 'Gum disease',
    aliases: ['periodontal disease', 'periodontitis', 'gingivitis'],
    category: 'other',
    familyHistoryRelevance: 'moderate',
    description: 'Inflammation and infection of the gums and the bone supporting the teeth.',
    riskContext:
      'Has a familial component and shares risk factors with heart disease and diabetes. Daily habits genuinely determine the outcome.',
    planTags: ['tobacco', 'diet-sugar', 'screening', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('gumdisease'),
  },
  {
    id: 'endometriosis',
    name: 'Endometriosis',
    aliases: ['endo', 'pelvic pain condition'],
    category: 'other',
    familyHistoryRelevance: 'strong',
    description: 'Tissue similar to the womb lining growing outside the womb, often causing pain.',
    riskContext:
      'A sister or mother with endometriosis raises risk several-fold, and diagnosis is often delayed for years. Family history is a reason to push for answers sooner.',
    planTags: ['screening', 'activity', 'mental-wellbeing', 'stress'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('endometriosis'),
  },
  {
    id: 'uterine_fibroids',
    name: 'Uterine fibroids',
    aliases: ['fibroids', 'myoma', 'leiomyoma'],
    category: 'other',
    familyHistoryRelevance: 'strong',
    description: 'Non-cancerous growths in the muscle of the womb.',
    riskContext:
      'Familial clustering is well documented. They are benign, but heavy bleeding is worth investigating rather than enduring.',
    planTags: ['screening', 'weight', 'diet-quality', 'activity'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('uterinefibroids'),
  },
  {
    id: 'chronic_fatigue_syndrome',
    name: 'Chronic fatigue syndrome',
    aliases: ['ME/CFS', 'myalgic encephalomyelitis', 'post-viral fatigue'],
    category: 'other',
    familyHistoryRelevance: 'moderate',
    description: 'Long-lasting, disabling fatigue that is not relieved by rest.',
    riskContext:
      'Familial clustering is reported. Pacing matters more than pushing: if this is your picture, treat the activity items here as a ceiling, not a target.',
    planTags: ['sleep', 'stress', 'mental-wellbeing', 'diet-quality'],
    sourceName: MEDLINEPLUS,
    sourceUrl: mp('chronicfatiguesyndrome'),
  },
  {
    id: 'frailty_and_falls',
    name: 'Frailty and falls',
    aliases: ['falls', 'frailty', 'loss of muscle', 'sarcopenia'],
    category: 'other',
    familyHistoryRelevance: 'moderate',
    description: 'Age-related loss of strength and reserve that makes falls and illness more likely.',
    riskContext:
      'Shaped by shared family habits at least as much as by genes, and strength training reverses a surprising amount of it at any age.',
    planTags: ['activity', 'bone-strength', 'diet-quality', 'weight'],
    sourceName: MEDLINEPLUS,
    sourceUrl: MP_INDEX,
  },
];
